sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y python

matrix:
  include:
    - language: cpp
      before_script:
        - cd firmware/esp8266
      script:
        - make

    - language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-27.0.2
          - android-27
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
        - yes | sdkmanager "platforms;android-27"
      before_script:
        - cd client/android
      script:
        - ./gradlew assemble
        
    - language: node_js
      node_js:
        - "iojs"
      before_script:
        - cd client/html
      script:
        - npm install
        - npm run-script build-prod

